version: 4.27.2
services:
  bot:
    image: "bot"
    container_name: "bot"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    command: sh -c "python3 -m bot"
    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"

